// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleApp.Api.Data;

#nullable disable

namespace PeopleApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeopleApp.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Coca-Cola 600ml",
                            Price = 22m,
                            Sku = "BEB-COCA-600"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Agua Natural 1L",
                            Price = 15m,
                            Sku = "BEB-AGUA-1L"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Jugo Naranja 500ml",
                            Price = 20m,
                            Sku = "BEB-JUG-NAR-500"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Powerade 500ml",
                            Price = 28m,
                            Sku = "BEB-POW-500"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Café Americano 355ml",
                            Price = 25m,
                            Sku = "BEB-CAFE-AME-355"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Té Helado Limón 600ml",
                            Price = 24m,
                            Sku = "BEB-TE-LIM-600"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Papas Sabritas Original 45g",
                            Price = 18m,
                            Sku = "BOT-SAB-ORI-45"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Doritos Nacho 58g",
                            Price = 20m,
                            Sku = "BOT-DOR-NAC-58"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Cheetos Flamin Hot 52g",
                            Price = 20m,
                            Sku = "BOT-CHE-FH-52"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Ruffles Queso 50g",
                            Price = 20m,
                            Sku = "BOT-RUF-QUE-50"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Takis Fuego 56g",
                            Price = 22m,
                            Sku = "BOT-TAK-FUE-56"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Palomitas Mantequilla 90g",
                            Price = 26m,
                            Sku = "BOT-PAL-MAN-90"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Galletas Marías 170g",
                            Price = 18m,
                            Sku = "GAL-MAR-170"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Galletas Oreo 154g",
                            Price = 30m,
                            Sku = "GAL-ORE-154"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Gansito 50g",
                            Price = 20m,
                            Sku = "PAN-GAN-50"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Chocorroles 2 pzas",
                            Price = 26m,
                            Sku = "PAN-CHO-2"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Barra de Chocolate 45g",
                            Price = 15m,
                            Sku = "DUL-CHO-45"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Gomitas Enchiladas 80g",
                            Price = 18m,
                            Sku = "DUL-GOM-ENC-80"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Sándwich Jamón y Queso",
                            Price = 45m,
                            Sku = "ALI-SAN-JQ"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Ensalada César",
                            Price = 55m,
                            Sku = "ALI-ENS-CES"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Yogurt Fresa 125g",
                            Price = 14m,
                            Sku = "LAC-YOG-FRE-125"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Leche Entera 1L",
                            Price = 28m,
                            Sku = "LAC-LEC-ENT-1L"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "Queso Panela 200g",
                            Price = 48m,
                            Sku = "LAC-QUE-PAN-200"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Jamón de Pavo 250g",
                            Price = 52m,
                            Sku = "CAR-JAM-PAV-250"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "Pan de Caja Blanco",
                            Price = 38m,
                            Sku = "PAN-CAJ-BLA"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "Tortillas de Harina 10 pzas",
                            Price = 32m,
                            Sku = "ALI-TOR-HAR-10"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "Arroz 1kg",
                            Price = 30m,
                            Sku = "DES-ARR-1K"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "Frijol Negro 1kg",
                            Price = 34m,
                            Sku = "DES-FRI-NEG-1K"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "Atún en Agua 140g",
                            Price = 22m,
                            Sku = "DES-ATU-AGU-140"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "Aceite Vegetal 900ml",
                            Price = 55m,
                            Sku = "DES-ACE-VEG-900"
                        });
                });

            modelBuilder.Entity("PeopleApp.Api.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("PeopleApp.Api.Entities.PurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("PeopleApp.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEmailEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PeopleApp.Api.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<double>("Estatura")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PeopleApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PeopleApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PeopleApp.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleApp.Api.Entities.PurchaseLine", b =>
                {
                    b.HasOne("PeopleApp.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleApp.Api.Entities.Purchase", "Purchase")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PeopleApp.Api.Entities.Purchase", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
